services:
  db:
    image: postgres:16-alpine
    environment:
      POSTGRES_USER: cofre
      POSTGRES_PASSWORD: cofre
      POSTGRES_DB: cofre
    ports:
      - "5432:5432"
    volumes:
      - cofre_pg:/var/lib/postgresql/data

volumes:
  cofre_pg:
